### ISSUE TITLE
Yleiset palautusohjeet -linkki ei toimi

### ISSUE THREAD

**Issue by peksii** [teraton/jotu#15]
Linkki löytyy "Toiminnallisen määrittelyn vaatimukset" ja "Asiakasvaatimusten vaatimukset" kohdista. 
Linkkiä painettaessa ei tapahdu mitään, vaikka muiden linkkien tapaan pitäisi selaimen siirtyä "Yleiset palautusohjeet" kohtaan.

**Comment by mikaelfil** [comment]
Palautusohjeen linkki on muotoa http://www.cs.tut.fi/kurssit/TIE-02300/harjoitustyo/index.html#_Yleiset_palautusohjeet_1. Jos sen korjaa http://www.cs.tut.fi/kurssit/TIE-02300/harjoitustyo/index.html#_Yleiset_palautusohjeet eli jättää tuon _1 lopusta pois, linkki toimii.

**Comment by mleppanen** [comment]
Korjattu.
