### ISSUE TITLE
Sivupalkin muotoilu on viallinen pääsivulla

### ISSUE THREAD

**Issue by Jovasa** [teraton/jotu#18]
Pääsivulla sivupalkissa pääsivu ja harjoitustyö ovat samalla rivillä ja Luentojen ja Materiaalin välissä on tyhjä rivi.

Toistaminen: navigoi kurssin sivustojen pääsivulle.

**Comment by systa** [comment]
Korjattu.

**Comment by Jovasa** [comment]
Ei se kyllä vieläkään ole samanlainen

<td style="font-size:150%; padding: 0cm; background: rgb(239, 239, 255) none repeat scroll 0% 50%; -moz-background-clip: initial; -moz-background-origin: initial; -moz-background-inline-policy: initial; width: 100px;" valign="top">

pitäisi tod näk olla

<td style="width:128.25pt;background:#EFEFFF;padding:
  0cm 0cm 0cm 0cm;-moz-background-clip: initial;-moz-background-origin: initial;
  -moz-background-inline-policy: initial;background-position-x:0%;background-position-y:50%;
  background-attachment:scroll" valign="top" width="171">

**Comment by systa** [comment]
Tarkennuskysymys:
Tarkoitatko jotain muuta bugia, ja puhumme siis pääsivusta (http://www.cs.tut.fi/kurssit/TIE-02300/)?  Kyllä ne rivinvaihdot nyt näyttäisi olevan kunnossa, enkä näe tyhjää riviä.
Se, että navigointipalkki on erilainen joillakin sivuilla on toinen bugi jonka korjaaminen on edelleen kesken (ja issue siis auki siis auki)
KTS: https://github.com/teraton/jotu/issues/4
Se mikä ton tyylin pitäisi tarkkaan ottaen olla, on myös vielä auki.

**Comment by Jovasa** [comment]
Joo taitaa olla toi numero 4 kyseessä
