### ISSUE TITLE
Harjoitustyön dokumenttipohjan pdf-versio on vanha

### ISSUE THREAD

**Issue by RowEchelonForm** [teraton/jotu#21]
Sivun "harjoitustyö" alaosassa harjoitustyön toiminnallisen määrittelyn dokumenttipohjan pdf-versio ([ sovellusohje_hytt_drmaarittely.pdf ]) on vanhempi kuin doc-versio (2.6 vs 2.7).

**Comment by mleppanen** [comment]
Ongelma on HYTT:n puolella, mutta pistän palautetta eteenpäin.
