### ISSUE TITLE
Linkki opinto-oppaaseen

### ISSUE THREAD

**Issue by nezzzzzz** [teraton/jotu#23]
Linkkiä kurssin opinto-oppaan sivulle ei löydy Pääsivulta, mutta Harjoitustyö-osiosta löytyy. Muiltakaan sivuilta tätä linkkiä ei taida löytyä, mutta ei sitä kaikilla ehkä tarvitakaan.

**Comment by systa** [comment]
Kyllä. Lisätään.

**Comment by systa** [comment]
Nyt korjattu pääsivulla.
