### ISSUE TITLE
Palautesivulla voisi olla suora toiminnallisuus

### ISSUE THREAD

**Issue by mjanne** [teraton/jotu#27]
Palautesivulla voisi olla valmiiksi palautelaatikko, josta palautteen voisi jättää suoraan ilman sähköpostin lähettämistä. Tämä ainakin madaltaisi kynnystä lähettää palautetta ja palautetta tulisi enemmän.

Tai ainakin sivulla olevaan sähköpostiosoitteeseen voisi lisätä mailto -linkin käytön nopeuttamiseksi.

**Comment by systa** [comment]
Valitettavasti meidän järjestelmä ei tue palautelaatikon toteuttamista.

Mailto-linkki nähtiin liian houkuttelevaksi roskapostitusosoitteiden etsintä roboteille.
