### ISSUE TITLE
Viikkoharjoitukset -välilehdellä toistoa

### ISSUE THREAD

**Issue by Lawok** [teraton/jotu#30]
Tarpeetonta toistoa.
Saa aikaan sivujen vakavuuden kyseenalaistamisen.
![meh](https://cloud.githubusercontent.com/assets/9695821/5010767/3b662276-6a7f-11e4-8375-34d8003a477c.png)

**Comment by ta-jotu-ass** [comment]
Hyvä kun tuo asia on HUOMATTU eli HUOMATTU. 
No nyt kun nuo eivät enää ole ajankohtaisia, niin poistin tarkoituksella tehdyt lisä-huomiorivit.
