### ISSUE TITLE
Katoava Menu

### ISSUE THREAD

**Issue by Sanzennin** [teraton/jotu#39]
Sivupalkki katoaa kun valitaan:
Viikkoharjoitukset, Luennot, Materiaali TAI Palaute

Sivupalkin tyyli muuttuu kun valitaan:
Hajoitustyöt

Käytän Firefoxia Win7:ssa

**Comment by systa** [comment]
Pitkälti saman kuin https://github.com/teraton/jotu/issues/4, joten merkitään tämä duplikaatiksi.

Tällä hetkellä pääsivulla on sama palkki kuin sivuilla Luennot, Materiaali ja Palaute. Viikkoharj ja Harjoitustyö vaatii vielä tunkkausta.
