### ISSUE TITLE
Linkki ei toimi harjoitustyön ohjeissa

### ISSUE THREAD

**Issue by erkki-pekka** [teraton/jotu#42]
http://www.cs.tut.fi/kurssit/TIE-02300/harjoitustyo/index.html sivulla on hyperlinkki (http://www.cs.tut.fi/kurssit/TIE-02300/harjoitustyo/index.html#_Yleiset_palautusohjeet_2) tekstissä toiminnallisen määrittelyn vaatimukset -väliotsikon alla.

**Comment by teraton** [comment]
verified
