### ISSUE TITLE
Palaute-osion sähköpostiosoite

### ISSUE THREAD

**Issue by MiK546** [teraton/jotu#43]
[Palaute-osiossa](http://www.cs.tut.fi/kurssit/TIE-02300/palaute.html) oleva sähköpostiosoite voisi olla mailto:-linkkinä niin palautetta olisi helpompi lähettää vain painamalla linkkiä. Tällä hetkellä se on vain pelkkänä tekstinä.

**Comment by systa** [comment]
Näinhän se voisi.  Valitettavasti se houkuttelee myös roskapostilistojen keräilyrobotteja.
