### ISSUE TITLE
Sivuston osoite tarvitsee www.-osan toimiakseen

### ISSUE THREAD

**Issue by JalleenTurhaTunnusJokaJaaRoikkumaan** [teraton/jotu#7]
Sivusto ei toimi osoitteella
http://cs.tut.fi/kurssit/TIE-02300
Vaan vaatii alkuun www.-alun.
Tämä on käyttäjäystävällisyyden kannalta ikävä ominaisuus, joka voi johtaa huomattavaan sivustokävijämäärän laskuun.

**Comment by systa** [comment]
Tämä ei ole kurssin henkilökunnan käsissä.
