### ISSUE TITLE
Nälkä

### ISSUE THREAD

**Issue by Hermanni123** [teraton/jotu#8]

**Comment by Enmis** [comment]
Sama -.-

**Comment by EMMASANDFORD** [comment]
Nää harkat kyllä harvoi loppuu ajoissa, yrittäkää kestää

**Comment by teraton** [comment]
Hauskoja juttuja, ei tää tosin mikään bugiraportti oo...

**Comment by joonaskari** [comment]
Menninkäisiä

**Comment by joonaskari** [comment]
http://pna.fi/tty/

Oispa ruokaa...

**Comment by systa** [comment]
Söin hyvä aamupalan. Ei enää nälkä. Suljen tiketin.
